# Generated by Django 3.0.8 on 2020-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_header',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
