# Generated by Django 3.0.8 on 2020-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200929_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_header', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_header',
        ),
    ]
